project:
  type: website
  output-dir: _site

website:
  title: "blog"
  site-url: https://acastroaraujo.github.io/blog/
  open-graph: true
  twitter-card: true
  navbar:
    title: false
    left:
      - icon: house
        text: about
        href: https://acastroaraujo.github.io
      - icon: file-person
        text: cv
        href: https://acastroaraujo.github.io/cv/
      - icon: github
        text: github
        href: https://github.com/acastroaraujo
      - icon: chat-text
        text: blog
        href: index.qmd
    right:
      - icon: rss
        href: index.xml

format:
  html:
    theme: [cosmo, styles.scss]
    fig-align: center
    code-fold: show
    grid:
      sidebar-width: 100px
      margin-width: 500px

editor: visual

csl: american-journal-of-sociology.csl
