---
title: "Weasels"
description: |
  Cowards and Professional Integrity
author: andrés castro araújo
date: 2024-07-24
draft: true
---

::: {style="text-align: right; padding-left: 120px;"}
*And what may weasel words be? Why weasel words are words that suck all the life out of the words next to them, just as a weasel sucks an egg and leaves the shell.*

*— Stewart Chaplin*
:::

Avoid using [weasel words](https://en.wikipedia.org/wiki/Weasel_word) at all costs.

I have slowly interiorized this norm during my time in grad school. Without realizing it, I became annoyed

At first I thought it

hedges, a marker of polite speech.

inject uncertainty means you are humble and as a bonus you cannot be wrong.

it was just a sign of lazy thinking

The most important thing I've learned in grad school

“affect,” “determine,” “influence,” “shape,”

Ever since I started grad school there is one thing that faculty.

Sociologists use weasel words to insinuate causal claims without having to commit

Using weasel words means you are a coward and you lack professional integrity.

structural, enable, complicit

-   I truly believe that one day we as a website will make it out of the darkness of weird arbitrary "complicity" moralism and into the sunny daylight in between "the thing you do is connected to something/someone bad" and "the thing you do itself is a bad thing"

-   "Complicit" is almost always an unhelpful weasel-word. Either (a) the person is actually doing something to help someone do a bad thing. In which case, you can just say that. Or (b) they aren't, and so maybe they shouldn't be criticized at all.

Say what you mean. Bear witness. Iterate. John M. Ford, “De Vermis”.
