---
title: '"Better Theories"'
description: |
  Formal, pragmatic, aesthetic, and empirical virtues
author: andrés castro araújo
categories:
  - Theory
  - Sociology
date: 2024-01-11
bibliography: references.bib
---

The new editors of *Theory & Society* have a strange [statement of goals](https://link.springer.com/journal/11186/updates/26605018) with some minor platitudes about what makes for a good theory---e.g., "general, abstract, and amenable to empirical investigation."

But most of the statement is quite superficial in content and angry in tone.

So, what actually makes for a good "scientific theory"?

I'm just going to copy-paste this list of good principles:

> **FORMAL VIRTUES**
>
> -   **Testability**
>
>     The theory should express commitments about the world that in principle can be confirmed or falsified on the basis of empirical evidence. </br></br>
>
> -   **Internal Coherence**
>
>     The theory should be coherent and should not contain contradictions.
>
> **PRAGMATIC VIRTUES**
>
> -   **Fertility**
>
>     The theory should suggest new and exciting avenues of research. It should generate new research questions faster than it can answer them. </br></br>
>
> -   **Conservatism**
>
>     The theory should retain crucial bits of what came before and not break too quickly or too dramatically with tradition without a compelling reason for doing so.
>
> **AESTHETIC VIRTUES**
>
> -   **Simplicity**
>
>     The theory should posit only those entities, properties, causal relations, etc. that are necessary to account for the phenomenon.</br></br>
>
> -   **Elegance**
>
>     The theory should be compact and graceful.
>
> **EMPIRICAL VIRTUES**
>
> -   **Empirical Adequacy**
>
>     The theory should accommodate or fail to conflict with well-established phenomena.</br></br>
>
> -   **Prediction**
>
>     The theory should make accurate predictions and retrodictions, particularly concerning phenomena that would be surprising were the theory to be false.</br></br>
>
> -   **Explanation**
>
>     The theory should explain the phenomena in its domain either by showing how they follow from general laws of nature or by showing how they are produced, given rise to, or maintained by mechanisms.</br></br>
>
> -   **External Coherence**
>
>     The theory should be supported by (or at least consistent with) other well-accepted non-rival theories.</br></br>
>
> -   **Generality**
>
>     The theory should apply to more phenomena than its rivals.</br></br>
>
> -   **Unification**
>
>     The theory should unify diverse phenomena by showing them to be instances of a common pattern.
>
> From: @craver2013 [pp. 83-4]

*Note. @craver2013 advocate for a mechanism-based view of scientific explanation which nowadays has superseded the "covering law" approach to scientific explanation (i.e., good old-fashioned positivism). Mechanism-based explanations have been heavily endorsed by "analytical sociology" [e.g., @hedstrom1996; @hedstrom2005];* *unfortunately, most sociologists see this literature as being exclusively commited to rational-choice theory and agent-based modeling. Read the book!*
