---
title: "Fields and Goal-Directedness"
#description: |
  
author: andrés castro araújo
date: 2024-05-16
draft: true
---

rankings become fields

the external environments in organizational sociology are fields

ecologies are fields

only alternative to field theories is cybernetics

fields are real, not useful fictions

positions in fields should be replaced by individual-level fields?

look for discussion between ANT and fields, and how that person says that fields account for interests and motivation (goal-directedness), whereas ANT can't do it.

McShea fields have less baggage, not every field is a battle field

overlapping fields and jason ferguson

global fields (Go) and World Society

organizational fields in DiMaggio and Powell

JJ Gibson on affordances. "The information is in the light"

Dennet on information and Umwelt

...Lewin (1935) in his field theory argued that
behavior was "steered" by the objects in the current environment, through their activation of the individual's behavioral
goals associated with them (pp. 49-50).
