---
title: "Meaning-Making"
description: |
  Disambiguation.
author: andrés castro araújo
date: 2024-07-26
categories: 
  - Culture
  - Sociology
bibliography: references.bib
---

Most sociologists seem to believe that [meaning-making]{.smallcaps} is at the center of cultural sociology [e.g., @spillman2020]. But I have never encountered a coherent definition of what [meaning-making]{.smallcaps} is supposed be. It is mostly an empty signifier that stands in for all sorts of overlapping concepts—e.g., narrative, habitus, classification, repertoire, norm, script, preference, skill, belief, value, prototype, perception, representation, etc.

The idea of [meaning-making]{.smallcaps} is somehow *more* ambiguous than the concept of [culture]{.smallcaps}. It cannot be the center of gravity for an entire subfield. We should get rid of it.

In the meantime this how I make sense of [meaning-making]{.smallcaps}.

1.  Anything that can be described as an *expressive* activity produced within some authoritative "cultural" domain, such as art, music, film, literature, dance, and so on.

    This is not what most most cultural sociologists have in mind when they think of [meaning-making]{.smallcaps}. But it is what the [production of culture]{.smallcaps} perspective is all about [@peterson2004].

2.  *Information-processing.*

    We *hear* some spoken message, we *smell* something. We then react quickly, perhaps unconsciously, on the basis of some habitual way of seeing things that is grounded in personal experience. In other words, we [interpret]{.smallcaps} a stimulus via [categorization]{.smallcaps} and [association]{.smallcaps} [@goldberg].

    Is that *thing* a bird? Or is it a plane? This is [categorization]{.smallcaps} [@rosch1975]. In turn, the bird can elicit all sort of "connected" concepts, such as food, disease, sacred, dinosaur, and so on. This is [semantic association]{.smallcaps}.[^1]

3.  *Purpose.*

    "Meaning" is also something people try to *find* as they go around "making sense" of their everyday lives and the choices the make.

    Sociologists usually take one of two common approaches. First, the *meaning-as-motive approach* seeks to understand action in terms of goals and values. Second, the *meaning-as-justification* approach focuses on understanding the *reasons* people give to why-questions. The former finds the "true springs of action" in motivational concepts (e.g., desires, interests, values), whereas the latter sees "meaning" as something that works retroactively (e.g., narratives, accounts).[^2]

    So we have two different ways of thinking about "purpose" that *do not always* overlap: [cause]{.smallcaps} and [reason]{.smallcaps}.

[^1]: The notion of "connectedness" needs further clarification, but it's usually conceived as a "distance" along some kind of conceptual space.

[^2]: See @mills1940, @scott1968, @swidler1986, @vaisey2009, @small2021, and so on. The idea that "motives" and "talk of motives" are somehow at odds with each other is no longer prevalent.

*Note. If you combine information-processing and meaning-as-motive you end up with a modern rendition of Max Weber's [-@weber1978] interpretative sociology. This should be the actual "center of gravity" for cultural sociologists.*
