---
title: "Fields"
description: |
  What are we talking about?
author: andrés castro araújo
date: 2025-03-12
draft: true
---

The idea of "field" signals a shift in the study of goal-directed behavior.

It is a way to conceptualize non-localized influence... it is non-localized because it's information we gather from our surrounding environment.

<https://acastroaraujo-notebooks.netlify.app/posts/2024-05-08-goal-directed-systems/index.html>

The previous alternative to field theories is cybernetics.

Examples:

-   rankings

-   the external environments in organizational sociology, including what D&P call fields

-   ecologies

JLM

McShea: McShea fields have less baggage, not every field is a battle field

JJ Gibson on affordances. "The information is in the light"

Dennet on information and Umwelt

...Lewin (1935) in his field theory argued that behavior was "steered" by the objects in the current environment, through their activation of the individual's behavioral goals associated with them (pp. 49-50).

**Ecology**

Ecological models analyze the interaction between individual organisms and their environments; including interactions within and between species.

In sociology, the word "ecology" is usually interpreted as an "ecology of relationships"; the word environment is variously construed as being more about [social structure]{.allcaps} or [culture]{.allcaps}; and the word "species" is variously construed as being about different kinds of [identities]{.allcaps}. The analog of "species" in sociology is more straightforward when talking about different *organizational forms* (e.g., schools, hospitals, banks) competing for similar resources.

*Note. Ecological interactions also set the stage for evolutionary processes because they provide for a proper notion an entity's "fitness" to its environment.*