---
title: "Cowards"
description: |
  Hedges, Weasels, and Professional Integrity
author: andrés castro araújo
date: 2024-07-28
categories:
  - Ethics
bibliography: references.bib
---

::: {style="padding-left: 30%;"}
*And what may weasel words be? Why weasel words are words that suck all the life out of the words next to them, just as a weasel sucks an egg and leaves the shell.*

::: {style="text-align: right;"}
*—Stewart Chaplin*
:::
:::

I have finally lost all patience for [weasel words](https://en.wikipedia.org/wiki/Weasel_word). I react viscerally when I see people unnecessarily injecting ambiguity and uncertainty in their writing. And I feel a sort of catholic guilt when I catch myself doing it.

This feeling is not rooted in a preference for clear thinking, nor is it a disdain for ambiguity or lazy thinking. It has more to do with integrity. I am thinking about the kinds of words that create distance between yourself and what you say. This distance removes accountability. *And this is why cowards use them all the time.*

For example, sociologists use weasel words all the time to insinuate causal claims without having to commit to them---e.g., 'affect', 'influence', 'shape', and so on. Or they will describe someone or some policy as being 'complicit with' or 'enabling' something bad instead of describing them outright as *doing* something bad.

<aside>*Amateurs, dilettantes, hacks, cowboys, clones* 🎶</aside>

This feeling is not widespread. We are also told that injecting uncertainty or ambiguity into our writing is a mark of caution and humility, not cowardice. [Hedges](https://en.wikipedia.org/wiki/Hedge_(linguistics)) are a marker of *polite speech*. And American sociologists value politeness above all else *("We are not rude like the economists!").*

Injecting uncertainty and ambiguity in the things you say creates the image of humility and politeness. But it also insulates you from being wrong. *("A feature, not a bug").* You will never be wrong unless you make a commitment.

Do not be a coward.

::: {style="background-color: #F5F3ED; padding-left: 2em; padding-right: 2em; padding-top: 2em; padding-bottom: 2em; margin-left: 5em; margin-right: 5em; text-align: center;"}
Say what you mean. Bear witness. Iterate.

John M. Ford, “De Vermis”.[^1]
:::

[^1]: Taken from [this syllabus](https://kieranhealy.org/files/teaching/gradtheory.pdf).
